workspace:
  base: /var/www/owncloud
  path: apps/oauth2

branches: [master, release*]

pipeline:
  install-server:
    image: owncloudci/core
    pull: true
    version: ${OC_VERSION}
    db_type: ${DB_TYPE}
    db_name: ${DB_NAME=owncloud}
    db_host: ${DB_TYPE}
    db_username: autotest
    db_password: owncloud
    db_timeout: 120

  install-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/
      - php occ a:l
      - php occ a:e oauth2
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=owncloud
      - php occ log:manage --level 0

  owncloud-log:
    image: owncloud/ubuntu:16.04
    detach: true
    pull: true
    commands:
      - tail -f /var/www/owncloud/data/owncloud.log

  webui-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - BROWSER=chrome
      - SELENIUM_HOST=selenium
      - TEST_SERVER_URL=http://owncloud
      - SELENIUM_PORT=4444
      - PLATFORM=Linux
      - BEHAT_SUITE=${BEHAT_SUITE}
    commands:
      - chown www-data /var/www/owncloud -R
      - chmod 777 /var/www/owncloud/tests/acceptance/filesForUpload -R
      - cd /var/www/owncloud/tests/acceptance
      - chmod +x run.sh
      - ./run.sh --remote --config /var/www/owncloud/apps/oauth2/tests/acceptance/config/behat.yml
    when:
      matrix:
        TEST_SUITE: acceptance

  phpunit-unit-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
    - make test-php-unit-dbg
    when:
      matrix:
        TEST_SUITE: phpunit

  codecov:
    image: plugins/codecov:2
    secrets: [codecov_token]
    pull: true
    files:
    - '*.xml'
    paths:
    - tests/output
    when:
      event: [push, pull_request]
      matrix:
        COVERAGE: true


  notify:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: builds
    when:
      status: [ failure, changed ]
      event: [ push, tag ]

services:
  owncloud:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/var/www/owncloud/
    command: [ "/usr/local/bin/apachectl", "-e", "debug", "-D", "FOREGROUND" ]
    when:
      matrix:
        TEST_SUITE: acceptance

  selenium:
    image: selenium/standalone-chrome-debug:latest
    pull: true
    when:
      matrix:
        TEST_SUITE: acceptance

  mysql:
    image: mysql:5.5
    environment:
    - MYSQL_USER=autotest
    - MYSQL_PASSWORD=owncloud
    - MYSQL_DATABASE=${DB_NAME=owncloud}
    - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mysql

  pgsql:
    image: postgres:9.4
    environment:
    - POSTGRES_USER=autotest
    - POSTGRES_PASSWORD=owncloud
    - POSTGRES_DB=${DB_NAME=owncloud}
    when:
      matrix:
        DB_TYPE: pgsql

  oci:
    image: deepdiver/docker-oracle-xe-11g
    environment:
    - ORACLE_USER=system
    - ORACLE_PASSWORD=oracle
    - ORACLE_DB=${DB_NAME=owncloud}
    when:
      matrix:
        DB_TYPE: oci


matrix:
  include:
    # acceptance tests
    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: acceptance
      BEHAT_SUITE: webUIOauth2

    - PHP_VERSION: 5.6
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: acceptance
      BEHAT_SUITE: webUIOauth2

    # unit tests
    - PHP_VERSION: 7.2
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      COVERAGE: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: pgsql

    - PHP_VERSION: 7.2
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: oci
      DB_NAME: XE
      DB_USERNAME: autotest

    - PHP_VERSION: 5.6
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: sqlite

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: sqlite

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: sqlite


