name: Build dist

on:
  push:
    branches: [ release-0.6 ]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  build:
    uses: owncloud/reusable-workflows/.github/workflows/build.yml@main
